export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS'; 
export const SET_INGREDIENTS = 'SET_INGREDIENTS'; 
export const FETCH_FAILED = 'FETCH_FAILED'; 

//Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL'; 
export const AUTH_LOGOUT = 'AUTH_LOGOUT'; 

export const AUTH_REDIRECT_LINK = 'AUTH_REDIRECT_LINK'
